### ISSUE TITLE
missing text in 1.2 clRetainMemObject man page?

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/OpenCL-Registry#15]
Moved from internal issue 8573:

The Notes section of the 1.2 man page for clRetainMemObject begins:

"clCreateBuffer, clCreateSubBuffer, and clCreateImage, and perform an implicit retain."

That looks to be the end of a sentence, so I assume there was at one time some preceding text that somehow got deleted.  It certainly doesn't mean anything now. I'm not familiar enough with the API to propose alternative language.

**Comment by Oblomov** [comment]
I think there's just an extra `, and`. The PDF specification just mentions that

> clCreateBuffer, clCreateSubBuffer and clCreateImage perform an implicit retain.

**Comment by oddhack** [comment]
Closed by #18
