### ISSUE TITLE
"bitwise exclusive or" (^) listed as "bitwise not"

### ISSUE THREAD

**Issue by Dithermaster** [KhronosGroup/OpenCL-Registry#25]
https://www.khronos.org/registry/OpenCL/sdk/2.1/docs/man/xhtml/operators.html says both "^" and "~" are "bitwise not" but the former is actually "bitwise exclusive or". This looks like simple copy/paste error that is trivial to fix in the various versions of https://github.com/KhronosGroup/OpenCL-Registry/blob/master/sdk/2.1/docs/man/operators.xml

I will prepare a pull request that fixes this.

**Comment by Dithermaster** [comment]
Pull request submitted: https://github.com/KhronosGroup/OpenCL-Registry/pull/26

**Comment by oddhack** [comment]
I accepted the PR and regenerated the output HTML.
