### ISSUE TITLE
New OpenCL logo

### ISSUE THREAD

**Issue by capitalknew** [KhronosGroup/OpenCL-Registry#32]
I want to suggest new OpenCL logo. It drew by myself. If I wrote to wrong repository or location, tell me please, where I can suggest new Khronos groups logos? (but I have only OpenCL logo idea)

![opencl-unofficial-logo](https://user-images.githubusercontent.com/28119043/31364978-facc6bc8-ad9a-11e7-8bb4-7ddfca281891.png)

**Comment by Andreyogld3d** [comment]
I like It!

**Comment by Khronoswebmaster** [comment]
Apple owns the trademark on OpenCL.
