### ISSUE TITLE
Typo in  OpenCL Device Queries table

### ISSUE THREAD

**Issue by fasbjx** [KhronosGroup/OpenCL-Registry#36]
Hi!

In table 3, OpenCL Device Queries, of The OpenCL Specification version v2.2-3
CL_DEIVCE_MAX_ WORK_ITEM_DIMENSIONS has to be read
CL_DEVICE_MAX_ WORK_ITEM_DIMENSIONS

**Comment by oddhack** [comment]
Please refile this on https://github.com/KhronosGroup/OpenCL-Docs .

**Comment by fasbjx** [comment]
Done
[https://github.com/KhronosGroup/OpenCL-Docs/issues/3](url)
