### ISSUE TITLE
Array to pointer const-correctness issues

### ISSUE THREAD

**Issue by presentfactory** [KhronosGroup/OpenCL-Registry#43]
Not sure if this is the correct place to report OpenCL API issues, but I couldn't really find a better place (not that people seem to care about OpenCL much anymore anyways...) so I shall put this here.

While working with the OpenCL 2.0 API (this also seems to exist in 2.2 as well), I noticed that I could not properly pass a constant array of C-style strings to `clCreateProgramWithSource` due to its signature (and others of the same nature) being `type const **` instead of `type const * const *`. Usually this would imply that the function will modify the memory pointed to in some way, but I cannot find any reference to this being the case in the functions in question. Additionally other non-double pointer parameters on the same functions seem to be const-correct such as the `lengths` parameter on `clCreateProgramWithSource`, so this seems to just be an oversight in these cases. A list of the functions which seem to do this are as follows (pretty much every reference to a `**` in the OpenCL 2.2 Specification, there may be more that the find did not reveal properly):

- `clEnqueueSVMMigrateMem` (Not sure about this one because I have never used it)
- `clCreateProgramWithSource`
- `clCreateProgramWithBinary`
- `clCompileProgram`
- `clEnqueueNativeKernel` (Again not sure due to not having used it, seems to imply something is replaced)

An example of how this causes issues is shown below, the "good" function signature works with both const and non-const arrays while the "bad" signature will fail with the const array:

```c++
#include <array>

// void foo(char const **) {} // Bad
void foo(char const * const *) {} // Good

int main() {
  std::array<char const *, 1U> const a{ "a" };
  std::array<char const *, 1U> b{ "b" };
  
  foo(a.data());
  foo(b.data());
}
```

Unless these functions do need to actually modify the memory being passed to them, I do not see why they should remain this way, unless they really do need it for some bizarre reason (or perhaps I read the API incorrectly), in which case I'd like to understand why. Thanks.

**Comment by oddhack** [comment]
Unfortunately, it isn't the right place - please move this over to https://github.com/KhronosGroup/OpenCL-Docs . I will try to make this clear in the README.

**Comment by oddhack** [comment]
This was moved to https://github.com/KhronosGroup/OpenCL-Docs/issues/9 , closing.
