### ISSUE TITLE
Broken link to latest spec

### ISSUE THREAD

**Issue by b-sumner** [KhronosGroup/OpenCL-Registry#49]
The link at bottom of this page appears broken :
 
https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/clCreateImage2D.html
 
 
http://www.khronos.org/registry/cl/specs/opencl-1.x-latest.pdf#page=59

**Comment by oddhack** [comment]
I don't even remember when the spec URL renaming happened, but will take a look at this.
