### ISSUE TITLE
Reconcile Duplicate cl.xml Files

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Registry#64]
There is an old cl.xml machine readable API description in this repo and we also added an updated cl.xml file in the OpenCL-Docs repo recently, via: https://github.com/KhronosGroup/OpenCL-Docs/commit/6163e510aba70daced330b7d7f54bc9b5b416252

Do we need to keep both XML files?  If so, we should update the cl.xml file in this repo so it is up-to-date.  If not, I think we can remove the cl.xml file in this repo.

**Comment by oddhack** [comment]
The one in this repo was incomplete, used only for enum block reservations. I'll take a look to make sure no content will be lost, and also to redirect pointers to it (e.g. there is a link from the registry index page), but my intention has been to get rid of it and use the far more complete one in the spec repo.

**Comment by oddhack** [comment]
Done. The index and README in this repo now point to OpenCL-Docs.
