### ISSUE TITLE
Error in clGetDeviceInfo for OpenCL 1.2 

### ISSUE THREAD

**Issue by AlexeySachkov** [KhronosGroup/OpenCL-Registry#71]
https://github.com/KhronosGroup/OpenCL-Registry/blob/822279186a7ca1fff9ca26a6ff2c85033fad17ec/sdk/1.2/docs/man/xhtml/clGetDeviceInfo.html#L1213-L1214

It should say `value returned will be 1.2`

**Comment by oddhack** [comment]
Can you construct a PR to fix this? Thanks.

**Comment by AlexeySachkov** [comment]
@oddhack, see #72
